import mujoco
import mujoco.viewer
import numpy as np
import matplotlib.pyplot as plt
import time

# load XLM model
model = mujoco.MjModel.from_xml_path('2R_robotics.xml') # _struct.MjModel 
                                                        # _struct.so (C file)
data = mujoco.MjData(model)

# pid controller
Kp = 25.0 # Proportional gain
Ki = 0.1  # Integral gain
Kd = 1.0  # Derivative gain

# Define our trajectory (a sinusoidal wave for each joints)
def desired_trajectory(t):
    """
    adjust amplitude and freq
    """
    amplitude = 0.5
    joint1_desired = amplitude * np.sin(1*np.pi*t)
    joint2_desired = amplitude * np.cos(1*np.pi*t)
    return joint1_desired, joint2_desired

# Computing the control signal generated by PID
def pid_control(target,current, prev_error, integral, dt):
    error = target - current
    integral += error + dt
    derivative = (error - prev_error) / dt
    control_signal = Kp * error + Ki * integral + Kd * derivative
    return control_signal, error, integral

# Launch the simulation
with mujoco.viewer.launch_passive(model, data) as viewer:
    start_time = time.time()
    prev_error = [0, 0]
    integral = [0, 0]

    # logging
    # trajectory1 = []
    # trajectory2 = []
    # signals1 = []
    # signals2 = []

    while viewer.is_running():
        current_time = time.time() - start_time
        dt = model.opt.timestep

